"""add soft delete to chats

Revision ID: d6c065bd6fe8
Revises: 988aef1f5abd
Create Date: 2026-04-18 14:07:43.645842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c065bd6fe8'
down_revision: Union[str, Sequence[str], None] = '988aef1f5abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('deleted_by_finder', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chats', sa.Column('deleted_by_claimer', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('chats', 'item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chats', 'finder_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chats', 'claimer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chats', 'claimer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chats', 'finder_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chats', 'item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('chats', 'deleted_by_claimer')
    op.drop_column('chats', 'deleted_by_finder')
    # ### end Alembic commands ###
